services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: journey
      POSTGRES_PASSWORD: "123456789"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local